### ISSUE TITLE
bazel vendor fails with Error: key "linux_i386" not found in dictionary

### ISSUE THREAD

**Issue by farcop** [chainguard-dev/rules_apko#70]
```
% bazel vendor --vendor_dir=vendored
...
INFO: Repository rules_apko~~apko~apko_linux_i386 instantiated at:
  <builtin>: in <toplevel>
Repository rule apko_repositories defined at:
  /private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/rules_apko~/apko/repositories.bzl:80:36: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_apko~~apko~apko_linux_i386':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/rules_apko~/apko/repositories.bzl", line 58, column 68, in _apko_repo_impl
                integrity = APKO_VERSIONS[repository_ctx.attr.apko_version][repository_ctx.attr.platform],
Error: key "linux_i386" not found in dictionary
ERROR: <builtin>: fetching apko_repositories rule //:rules_apko~~apko~apko_linux_i386: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/rules_apko~/apko/repositories.bzl", line 58, column 68, in _apko_repo_impl
                integrity = APKO_VERSIONS[repository_ctx.attr.apko_version][repository_ctx.attr.platform],
Error: key "linux_i386" not found in dictionary
```

**Comment by farcop** [comment]
Fix proposed https://github.com/chainguard-dev/rules_apko/pull/71
